### PR TITLE
Make the number of recent tracks customizable

### PR DESCRIPTION
**Pull request by giorgian**

### CODE REVIEW

**Comment by mihaiolteanu** [comment]
Do you feel a need for this?
While it is correct, I'm not sure yet that it is useful.

**Comment by giorgian** [comment]
It is for me, 25 is waaaay to low a number.
But of course, it's your project.

**Comment by mihaiolteanu** [comment]
What do you feel would be a correct number?

Did you notice that if you call vuiet-play-recent-track, listen to some more tracks and then call it again, it will still display the same list as when you called it the first time? What do you feel bout that?

**Comment by giorgian** [comment]
I'm setting it to a very high number, say 500. I really think it should be configurable, a hardcoded number doesn't seem right to me.

> Did you notice that if you call vuiet-play-recent-track, listen to some more tracks and then call it again, it will still display the same list as when you called it the first time? What do you feel bout that?

It's odd, I'm not really sure how it works. So far it only added one song to my recent list since I started using vuiet; but I only listened to a few songs since configuring my SK, don't know if it's related.

I haven't dug into the code, so I really can't say.

**Comment by mihaiolteanu** [comment]
How about displaying a fixed number of recent songs, say 15, but offer the possibility of displaying the next 15 number of songs with some predefined key combination?

> So far it only added one song to my recent list since I started using vuiet

I'm not sure if you've just started using last.fm also, or only vuiet. Meaning, I'm not sure if you have tons of recently listened tracks and you want to have access to those, or you believe this is gonna be useful in the future.

Anyway, I'm tending to agree with you, the loved tracks list limit is also configurable and is set to 500.

But anyway, just for the sake of having some fun, can you evaluate these two functions in a \*scratch\* buffer and then call `vuiet-play-recent-track`?

```
(defun vuiet-play-recent-track ()
  "Play one of the recent listened tracks."
  (interactive)
  (vuiet--ivy-play-song #'lastfm-user-get-recent-tracks 1 15))

(defun vuiet--ivy-play-song (source-fn page entries)
  "Choose a song from SONGS with ivy and play it."
  (let ((songs (funcall source-fn :limit entries :page page)))
    (cl-multiple-value-bind (artist-max-len song-max-len)
        (cl-loop for entry in songs
                 maximize (length (car entry)) into artist
                 maximize (length (cadr entry)) into song
                 finally (return (cl-values artist song)))
      (let ((keymap (copy-keymap minibuffer-local-map)))
        (define-key keymap (kbd "M-n")
          (lambda () (interactive)
            (vuiet--ivy-play-song source-fn
                                  (+ 1 page)
                                  entries)))
        (define-key keymap (kbd "M-p")
          (lambda () (interactive)
            (vuiet--ivy-play-song source-fn
                                  (if (> page 1) (- page 1) page)
                                  entries)))
        (ivy-read (format "Play song (page %s): " page)
                  (mapcar (lambda (song)
                       (list (format (s-format  "%-$0s   %-$1s" 'elt
                                                ;; Add the padding
                                                `(,artist-max-len ,song-max-len))
                                     ;; Add the actual artist and song.
                                     (car song) (cadr song))
                             (list (car song) (cadr song))))
                     songs)
                  :action (lambda (selection)
                            (vuiet-play (list (cadr selection))))
                  :keymap keymap)))))
```

This will just display the first 15 tracks, but then you can navigate to your next 15 listened tracks with `M-n` or go back with `M-p`. I'm just curious if this might be useful or not, though I'm still leaning towards your solution as of now.

Thanks!

**Comment by giorgian** [comment]
> How about displaying a fixed number of recent songs, say 15, but offer the possibility of displaying the next 15 number of songs with some predefined key combination?

This seems acceptable to me. But again, why 15? I like to set the number of displayed items per page to a high number everywhere I can (issue trackers, mail clients, feed readers...).

> I'm not sure if you've just started using last.fm also, or only vuiet. 

I already had a last.fm account, but I haven't been using it for several years, I had to recover my password just for vuiet.

By the way, more new played songs are appearing in the recent list. I'm sorry I can't experiment more right now.

> But anyway, just for the sake of having some fun, can you evaluate these two functions in a *scratch* buffer and then call vuiet-play-recent-track?

It's not working, or I'm not using it right: if I press `M-n` or `M-p` it gives "ivy-read: Command attempted to use minibuffer while in minibuffer". It may be something else wrong with my configuration, I'm messing  up with a lot of stuff lately.

**Comment by mihaiolteanu** [comment]
> I like to set the number of displayed items per page to a high number everywhere I can

I agree with that.
Make sure to also update the README page with this new customizable variable.

Thank you!

**Comment by mihaiolteanu** [comment]
This does not update the actual `vuiet-play-recent-track` function documentation string in vuiet.el.
This also does not update the customization section of the README.

**Comment by mihaiolteanu** [comment]
You've mixed up the comments....again. There is an extra quote in there
```
  "Play one of the recent listened tracks."
The number of tracks shown is equal to VUIET-RECENT-TRACKS-LIMIT."
```
I didn't see it until I've actually tried to use this.

Please consider opening an issue next time.

**Comment by giorgian** [comment]
I'm really sorry. My local code is correct, but I messed up the commit trying not to commit the whitespace noise.

What settings are you using to indent your code, so that I can use the same ones?

**Pull request merged**
